resolver: lts-12.14

packages:
- .
- location:
    git: https://github.com/capital-match/docusign-base
    commit: 43f97c3bad86a9bfa5a8ed69376e8d6822384133
  extra-dep: false
- location:
    git: https://github.com/capital-match/docusign-client
    commit: 00f19e54409bcad00b82e24f53927727a285671e
  extra-dep: false

